<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        /*
            promise는 콜백지옥과 같은 코드가 형성되지 않게(비동기 통신간에 순서를 정하기 쉽게) 하는 방안으로
            ES6에서 도입되었다.
            (현재 시점에 ES6가 지원되는 브라우저에서 작업하고 있기 때문에 promise 사용을 위해 바벨은 필요 없음)
        */

        /* 내부적으로 비동기 처리를 하고 promise를 반환하는 함수 */
        function increase(number) {

            /* 아래와 같은 개념이 promise 객체를 만들 때 발생한다. (유사한 상황) */
            // const asyncFunc = (resolve, reject) => {
            //     setTimeout(
            //         () => {
            //             const result = number + 10;

            //             return result;
            //         },
            //         1000
            //     );
            // }

            // asyncFunc(resolve, reject);

            /*
                promise 객체 생성 이유
                1. 비동기 처리 함수를 실행 시 성공, 실패에 대한 처리가 용이하게 reslove 및 reject를 제공한다. 
                2. promise 객체가 제공하는 메소드를 사용하기 위함(콜백 지옥 상황을 해소해 주기 때문(가독성 상승, 메소드 체이닝 방식 제공))
            */
            const promise = new Promise((resolve, reject) => {
                setTimeout (
                    () => {
                        const result = number + 10;

                        if(result > 50) {
                            const e = new Error('NumberTooBig');

                            return reject(e);
                        }

                        resolve(result);
                    },
                    1000
                );
            });
            return promise;
        }

        console.log(increase(0));

        /* 
            increase 함수 호출 후에는 promise가 반환된다. 
            이 promise는 resolve함수에 던져진 인수를 기억하고 있다. 
            이 promise를 통해 then함수를 호출하고 던져지는 콜백함수의 인수로 기억했던 reslove 함수의 인수를 넣어준다.
        */
        console.log(increase(0));

        increase(0)
            .then(number => {                   // promise 내부의 resolve가 호출되고 결과가 담기고 난 뒤가 then이 실행되는 시점
                console.log(number);

                return increase(number);        // increase(10);
            })
            .then(number => {
                console.log(number);

                return increase(number);        // increase(20);
            })
            .then(number => {
                console.log(number);

                return increase(number);        // increase(30);
            })
            .then(number => {
                console.log(number);

                return increase(number);        // increase(40);
            })
            .then(number => {
                console.log(number);

                return increase(number);        // increase(50);
            })
            .then(number => {
                console.log(number);
                console.log('end');
            })
            .catch(e => {                       // reject에 들어간 에러 객체를 콜백함수의 인수로 넣어준다.
                console.log(e, '가 발생했네');
            })
            .finally(() => {
                console.log('finally 실행...');
            });

    </script>
</body>
</html>